/**
 * Abilities data set.
 * @file Abiilities.ts
 * @author Dimitri Tsampiras
 * @since 1.0.0
 */

type AbilityName =
  | 'Air Lock'
  | 'Arena Trap'
  | 'Battle Armor'
  | 'Blaze'
  | 'Chlorophyll'
  | 'Clear Body'
  | 'Cloud Nine'
  | 'Color Change'
  | 'Compound Eyes'
  | 'Cute Charm'
  | 'Drizzle'
  | 'Damp'
  | 'Drought'
  | 'Early Bird'
  | 'Effect Spore'
  | 'Flame Body'
  | 'Flash Fire'
  | 'Forecast'
  | 'Guts'
  | 'Huge Power'
  | 'Hustle'
  | 'Hyper Cutter'
  | 'Illuminate'
  | 'Immunity'
  | 'Inner Focus'
  | 'Insomnia'
  | 'Intimidate'
  | 'Keen Eye'
  | 'Levitate'
  | 'Lightning Rod'
  | 'Limber'
  | 'Liquid Ooze'
  | 'Magma Armor'
  | 'Magnet Pull'
  | 'Marvel Scale'
  | 'Minus'
  | 'Natural Cure'
  | 'Oblivious'
  | 'Overgrow'
  | 'Own Tempo'
  | 'Pickup'
  | 'Plus'
  | 'Poison Point'
  | 'Pressure'
  | 'Pure Power'
  | 'Rain Dish'
  | 'Rock Head'
  | 'Rough Skin'
  | 'Run Away'
  | 'Sand Stream'
  | 'Sand Veil'
  | 'Serene Grace'
  | 'Shadow Tag'
  | 'Shed Skin'
  | 'Shell Armor'
  | 'Shield Dust'
  | 'Soundproof'
  | 'Speed Boost'
  | 'Static'
  | 'Stench'
  | 'Sticky Hold'
  | 'Sturdy'
  | 'Suction Cups'
  | 'Swarm'
  | 'Swift Swim'
  | 'Synchronize'
  | 'Thick Fat'
  | 'Torrent'
  | 'Trace'
  | 'Truant'
  | 'Vital Spirit'
  | 'Volt Absorb'
  | 'Water Absorb'
  | 'Water Veil'
  | 'White Smoke'
  | 'Wonder Guard';
