/**
 * Abilities data set.
 * @file Abiilities.ts
 * @author Dimitri Tsampiras
 * @since 1.0.0
 */

export interface Ability {
  name: AbilityName;
}

export type AbilityName =
  | 'air lock'
  | 'arena trap'
  | 'battle armor'
  | 'blaze'
  | 'chlorophyll'
  | 'clear body'
  | 'cloud nine'
  | 'color change'
  | 'compound eyes'
  | 'cute charm'
  | 'drizzle'
  | 'damp'
  | 'drought'
  | 'early bird'
  | 'effect spore'
  | 'flame body'
  | 'flash fire'
  | 'forecast'
  | 'guts'
  | 'huge power'
  | 'hustle'
  | 'hyper cutter'
  | 'illuminate'
  | 'immunity'
  | 'inner focus'
  | 'insomnia'
  | 'intimidate'
  | 'keen eye'
  | 'levitate'
  | 'lightning rod'
  | 'limber'
  | 'liquid ooze'
  | 'magma armor'
  | 'magnet pull'
  | 'marvel scale'
  | 'minus'
  | 'natural cure'
  | 'oblivious'
  | 'overgrow'
  | 'own tempo'
  | 'pickup'
  | 'plus'
  | 'poison point'
  | 'pressure'
  | 'pure power'
  | 'rain dish'
  | 'rock head'
  | 'rough skin'
  | 'run away'
  | 'sand stream'
  | 'sand veil'
  | 'serene grace'
  | 'shadow tag'
  | 'shed skin'
  | 'shell armor'
  | 'shield dust'
  | 'soundproof'
  | 'speed boost'
  | 'static'
  | 'stench'
  | 'sticky hold'
  | 'sturdy'
  | 'suction cups'
  | 'swarm'
  | 'swift swim'
  | 'synchronize'
  | 'thick fat'
  | 'torrent'
  | 'trace'
  | 'truant'
  | 'vital spirit'
  | 'volt absorb'
  | 'water absorb'
  | 'water veil'
  | 'white smoke'
  | 'wonder guard';
