type ItemName =
  | 'black belt'
  | 'black glasses'
  | 'bright powder'
  | 'charcoal'
  | 'choice band'
  | 'dragon fang'
  | 'energy powder'
  | 'focus band'
  | 'hard stone'
  | 'kings rock'
  | 'heavy ball'
  | 'ice berry'
  | 'king\'s rock'
  | 'leftovers'
  | 'magnet'
  | 'metal coat'
  | 'miracle seed'
  | 'mystic water'
  | 'never-melt ice'
  | 'poison barb'
  | 'quick claw'
  | 'scope lens'
  | 'sharp beak'
  | 'soft sand'
  | 'spell tag'
  | 'twisted spoon'
